### ISSUE TITLE
More logs ?

### ISSUE THREAD

**Issue by Tom-Rivero** [ani8897/RSSI-based-Localization-using-ESP32#1]
Hello, I would like to know if you have any other log files to share ?
Ideally I am looking for logs of a path in the room with their associated coordinates to see how RSSIs behave with a moving target.
Looking forward to your reply, thanks.

**Comment by ani8897** [comment]
Hey! I didn't understand your question completely. Please feel free to shoot an email at anikets@illinois.edu and we can discuss more on the topic.
